INSERT INTO public.jobs (id, title, department, type, location, salary, "salaryMin", "salaryMax", skills, description, icon, status, "applicationUrl", created_at, updated_at)
VALUES
  (gen_random_uuid(), 'Senior Frontend Engineer', 'Engineering', 'Full-time', 'Remote / Hybrid', '$120k - $160k', 120000, 160000, ARRAY['React', 'TypeScript', 'Next.js', 'GraphQL'], 'Lead frontend development for enterprise applications. Mentor junior developers and drive technical decisions.', 'https://img.icons8.com/3d-fluency/94/web.png', 'ACTIVE', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Backend Engineer', 'Engineering', 'Full-time', 'On-site', '$110k - $150k', 110000, 150000, ARRAY['Node.js', 'Python', 'AWS', 'Microservices'], 'Build scalable backend systems and APIs. Work with modern cloud technologies and distributed systems.', 'https://img.icons8.com/3d-fluency/94/server.png', 'ACTIVE', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Full Stack Developer', 'Engineering', 'Full-time', 'Remote', '$100k - $140k', 100000, 140000, ARRAY['React', 'Node.js', 'MongoDB', 'Docker'], 'Work across the entire stack to deliver end-to-end solutions. Collaborate with cross-functional teams.', 'https://img.icons8.com/3d-fluency/94/under-computer.png', 'ACTIVE', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Product Designer', 'Design', 'Full-time', 'Hybrid', '$90k - $130k', 90000, 130000, ARRAY['Figma', 'UI/UX', 'Prototyping', 'User Research'], 'Design beautiful and intuitive user experiences for web and mobile applications.', 'https://img.icons8.com/3d-fluency/94/paint-palette.png', 'ACTIVE', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'DevOps Engineer', 'Infrastructure', 'Full-time', 'Remote / On-site', '$115k - $155k', 115000, 155000, ARRAY['Kubernetes', 'AWS', 'CI/CD', 'Terraform'], 'Manage infrastructure, automate deployments, and ensure system reliability at scale.', 'https://img.icons8.com/3d-fluency/94/cloud.png', 'ACTIVE', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'AI/ML Engineer', 'Data Science', 'Full-time', 'On-site', '$130k - $180k', 130000, 180000, ARRAY['Python', 'TensorFlow', 'PyTorch', 'MLOps'], 'Build and deploy machine learning models. Research and implement AI solutions for clients.', 'https://img.icons8.com/3d-fluency/94/brain-3--v1.png', 'ACTIVE', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'QA Automation Engineer', 'Quality', 'Full-time', 'Remote', '$95k - $125k', 95000, 125000, ARRAY['Selenium', 'Jest', 'Cypress', 'Test Automation'], 'Design and implement automated testing solutions to ensure product quality.', 'https://img.icons8.com/3d-fluency/94/automatic.png', 'ACTIVE', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Technical Lead', 'Engineering', 'Full-time', 'Hybrid', '$150k - $200k', 150000, 200000, ARRAY['Architecture', 'Leadership', 'Full Stack', 'Mentoring'], 'Lead technical projects and guide teams through architecture and development decisions.', 'https://img.icons8.com/3d-fluency/94/conference.png', 'ACTIVE', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Mobile Developer', 'Mobile', 'Full-time', 'Remote', '$105k - $145k', 105000, 145000, ARRAY['React Native', 'Flutter', 'iOS', 'Android'], 'Build cross-platform mobile applications with native performance and user experience.', 'https://img.icons8.com/3d-fluency/94/smartphone.png', 'ACTIVE', NULL, NOW(), NOW());

INSERT INTO public.internships (id, title, department, duration, location, stipend, "stipendAmount", skills, description, icon, status, "applicationUrl", created_at, updated_at)
VALUES
  (gen_random_uuid(), 'Frontend Developer Intern', 'Engineering', '3-6 months', 'Remote / Hybrid', '$1,500/month', 1500, ARRAY['React', 'TypeScript', 'Tailwind CSS', 'Next.js'], 'Build responsive, high-performance web applications with modern frameworks. Work closely with senior developers to create exceptional user experiences.', 'https://img.icons8.com/3d-fluency/94/web.png', 'ACTIVE', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Backend Developer Intern', 'Engineering', '3-6 months', 'Remote / On-site', '$1,800/month', 1800, ARRAY['Node.js', 'Python', 'MongoDB', 'REST APIs'], 'Design and implement scalable server-side architectures, APIs, and database solutions for enterprise applications.', 'https://img.icons8.com/3d-fluency/94/server.png', 'ACTIVE', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Mobile App Intern', 'Mobile', '4-6 months', 'Hybrid', '$1,600/month', 1600, ARRAY['React Native', 'Flutter', 'iOS', 'Android'], 'Develop cross-platform mobile applications with a focus on performance, user experience, and clean code architecture.', 'https://img.icons8.com/3d-fluency/94/smartphone.png', 'ACTIVE', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'UI/UX Design Intern', 'Design', '3-4 months', 'Remote', '$1,200/month', 1200, ARRAY['Figma', 'Adobe XD', 'User Research', 'Prototyping'], 'Create intuitive user interfaces and experiences for web and mobile applications with mentorship from senior designers.', 'https://img.icons8.com/3d-fluency/94/paint-palette.png', 'ACTIVE', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'AI/ML Intern', 'Data Science', '6-8 months', 'On-site', '$2,000/month', 2000, ARRAY['Python', 'TensorFlow', 'PyTorch', 'Data Analysis'], 'Work on cutting-edge AI projects, from model development to deployment, with guidance from our ML team.', 'https://img.icons8.com/3d-fluent/100/robot-6.png', 'ACTIVE', NULL, NOW(), NOW()),
  (gen_random_uuid(), 'DevOps Intern', 'Infrastructure', '3-6 months', 'Remote', '$1,700/month', 1700, ARRAY['AWS', 'Docker', 'Kubernetes', 'CI/CD'], 'Manage cloud infrastructure, automate deployments, and ensure system reliability and scalability.', 'https://img.icons8.com/3d-fluency/94/cloud.png', 'ACTIVE', NULL, NOW(), NOW());
